image: maven:3-jdk-7

stages:
  - build

services:
  - mysql:5.5
  - postgres:latest

variables:
  MYSQL_DATABASE: test
  MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
  POSTGRES_DB: test
  POSTGRES_USER: postgres
  POSTGRES_PASSWORD: ""

build:
  stage: build
  script: mvn package
